
FloatLayout:
    canvas:
        Color:
            rgba: 0,0,0,1
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        orientation:'vertical'
        size_hint: 0.4, 0.4
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        spacing: 0
        padding: 0
        Image:
            source: 'icones/logo.png'

        Image:
            source: 'icones/inclusiveWAY.png'

